import os
from string import Template
from typing import List, Union

HTML_DOCUMENT = Template("""
<!--AUTOGENERATED https://github.com/WalkTheDocs/book_designingMath/blob/master/generateHome.py -->
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <title>Designing Math</title>
</head>

<body>
    <h1>
        <ruby>
            <rb>Designing Math</rb>
            <rp>（</rp>
            <rt>デザイニング・マス</rt>
            <rp>）</rp>
        </ruby>
    </h1>

    <h2>TOC</h2>
    $children
</body>

</html>
""")
HTML_LINK = Template('<a href="./$chapter/$ch/index.html">$ch</a>')


def wrapWith(tag: str, children: Union[List[str], str]) -> str:
    if isinstance(children, list):
        output = f'<{tag}>'
        for child in children:
            output += child
        output += f'</{tag}>'
    else:
        output = f'<{tag}>{children}</{tag}>'
    return output


def main():
    """
    ファイル構成によって、トップディレクトリのindex.htmlを自動生成する
    """
    chapter_dirs = [d for d in os.listdir('.') if d.startswith('Chapter')]
    chapter_dirs.sort()

    chapters_html = []
    for chapter_dir in chapter_dirs:
        ch_dirs = [d for d in os.listdir(chapter_dir)
                   if not d.startswith('.') and d != 'exercises']
        ch_dirs.sort()

        links = [HTML_LINK.substitute(
            chapter=chapter_dir, ch=ch_dir) for ch_dir in ch_dirs]
        list_items = [wrapWith('li', link) for link in links]
        ul = wrapWith('ul', list_items)
        chapter_html = wrapWith('li', [chapter_dir, ul])
        chapters_html.append(chapter_html)

    children = wrapWith('ul', chapters_html)
    print(HTML_DOCUMENT.substitute(children=children))


if __name__ == '__main__':
    main()
